name: 01 - Building Blocks
on:
  - workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Helloy
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: The Bengt Step
        run: |
          echo "I will win"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye, World!"
