name: 04-using-actions.yaml
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.1
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Debug paths / npm versions
        run: |
          node -v
          npm -v
          ls -la
          ls -la 04-using-actions/react-app
          test -f 04-using-actions/react-app/package.json && echo "package.json exists"
          test -f 04-using-actions/react-app/package-lock.json && echo "package-lock.json exists"
      - name: Install dependencies
        working-directory: ./04-using-actions/react-app
        run: npm ci
